import {
  Driver,
  DeliveryOffer,
  ActiveDelivery,
  CompletedDelivery,
  EarningsData,
  Payout,
} from "@/types";

export const mockDriver: Driver = {
  id: "drv_001",
  firstName: "Thabo",
  lastName: "Molefe",
  phone: "+27 72 845 3921",
  email: "thabo.m@email.co.za",
  avatar: "",
  rating: 4.87,
  totalDeliveries: 1247,
  vehicle: {
    type: "motorcycle",
    make: "Honda",
    model: "CBR 250",
    plate: "GP 847-293",
    color: "Black",
  },
  documents: [
    { type: "South African ID", status: "verified" },
    { type: "Driver's License", status: "verified" },
    { type: "Vehicle Registration", status: "verified" },
    { type: "PrDP (Professional Driving Permit)", status: "verified" },
    { type: "Proof of Address", status: "verified" },
  ],
  isOnline: false,
  currentLocation: { lat: -26.1076, lng: 28.0567 }, // Sandton area
  joinedDate: "2024-03-15",
};

export const mockOffer: DeliveryOffer = {
  id: "offer_101",
  restaurant: {
    name: "Nando's Sandton",
    address: "Shop 12, Nelson Mandela Square, Sandton",
    location: { lat: -26.1076, lng: 28.0567 },
    phone: "+27 11 784 2310",
  },
  customer: {
    name: "Lerato K.",
    area: "Fourways",
    address: "28 Uranium St, Fourways, 2191",
    location: { lat: -26.0225, lng: 28.0125 },
    phone: "+27 82 334 5511",
  },
  distanceToPickup: 1.2,
  distancePickupToDropoff: 8.4,
  estimatedPay: 65.0,
  estimatedTip: 15.0,
  estimatedTime: 22,
  items: [
    { name: "Full Chicken (Hot)", quantity: 1 },
    { name: "Regular Chips", quantity: 2 },
    { name: "Coleslaw (Large)", quantity: 1 },
    { name: "Coca-Cola 500ml", quantity: 2, notes: "Ice cold" },
  ],
  specialInstructions: "Extra hot sauce packets please",
  orderId: "ORD-48291",
  expiresAt: Date.now() + 20000,
};

export const mockActiveDelivery: ActiveDelivery = {
  id: "del_201",
  orderId: "ORD-48291",
  currentStep: "at_restaurant",
  restaurant: {
    name: "Nando's Sandton",
    address: "Shop 12, Nelson Mandela Square, Sandton",
    location: { lat: -26.1076, lng: 28.0567 },
    phone: "+27 11 784 2310",
  },
  customer: {
    name: "Lerato K.",
    area: "Fourways",
    address: "28 Uranium St, Fourways, 2191",
    location: { lat: -26.0225, lng: 28.0125 },
    phone: "+27 82 334 5511",
    deliveryInstructions:
      "Gate code: #4523. Leave at the front door if no answer. Ring bell twice.",
  },
  items: [
    { name: "Full Chicken (Hot)", quantity: 1 },
    { name: "Regular Chips", quantity: 2 },
    { name: "Coleslaw (Large)", quantity: 1 },
    { name: "Coca-Cola 500ml", quantity: 2, notes: "Ice cold" },
  ],
  specialInstructions: "Extra hot sauce packets please",
  pickupCode: "4829",
  deliveryOtp: "7351",
  estimatedPay: 65.0,
  estimatedTip: 15.0,
  distanceToPickup: 1.2,
  distancePickupToDropoff: 8.4,
  estimatedTime: 22,
  acceptedAt: new Date(Date.now() - 600000).toISOString(),
};

export const mockCompletedDeliveries: CompletedDelivery[] = [
  {
    id: "del_200",
    orderId: "ORD-48290",
    restaurant: { name: "Ocean Basket Rosebank", address: "The Zone, Rosebank" },
    customer: { area: "Parktown" },
    earnings: { deliveryFee: 45.0, tip: 20.0, bonus: 0, total: 65.0 },
    distance: 5.2,
    duration: 18,
    completedAt: new Date(Date.now() - 3600000).toISOString(),
    rating: 5,
  },
  {
    id: "del_199",
    orderId: "ORD-48289",
    restaurant: { name: "Steers Melrose", address: "Melrose Arch, Melrose" },
    customer: { area: "Illovo" },
    earnings: { deliveryFee: 38.0, tip: 10.0, bonus: 5.0, total: 53.0 },
    distance: 3.8,
    duration: 14,
    completedAt: new Date(Date.now() - 7200000).toISOString(),
    rating: 4,
  },
  {
    id: "del_198",
    orderId: "ORD-48288",
    restaurant: { name: "McDonald's Rivonia", address: "Rivonia Crossing, Rivonia" },
    customer: { area: "Bryanston" },
    earnings: { deliveryFee: 42.0, tip: 0, bonus: 0, total: 42.0 },
    distance: 4.5,
    duration: 16,
    completedAt: new Date(Date.now() - 10800000).toISOString(),
  },
  {
    id: "del_197",
    orderId: "ORD-48287",
    restaurant: { name: "Spur Cresta", address: "Cresta Shopping Centre" },
    customer: { area: "Northcliff" },
    earnings: { deliveryFee: 52.0, tip: 25.0, bonus: 10.0, total: 87.0 },
    distance: 7.1,
    duration: 25,
    completedAt: new Date(Date.now() - 86400000).toISOString(),
    rating: 5,
  },
  {
    id: "del_196",
    orderId: "ORD-48286",
    restaurant: { name: "KFC Sandton City", address: "Sandton City Mall" },
    customer: { area: "Woodmead" },
    earnings: { deliveryFee: 40.0, tip: 15.0, bonus: 0, total: 55.0 },
    distance: 6.3,
    duration: 20,
    completedAt: new Date(Date.now() - 90000000).toISOString(),
    rating: 5,
  },
  {
    id: "del_195",
    orderId: "ORD-48285",
    restaurant: { name: "Debonairs Randburg", address: "Randburg CBD" },
    customer: { area: "Linden" },
    earnings: { deliveryFee: 35.0, tip: 10.0, bonus: 0, total: 45.0 },
    distance: 3.2,
    duration: 12,
    completedAt: new Date(Date.now() - 93600000).toISOString(),
  },
  {
    id: "del_194",
    orderId: "ORD-48284",
    restaurant: { name: "Rocomamas Parkhurst", address: "4th Ave, Parkhurst" },
    customer: { area: "Greenside" },
    earnings: { deliveryFee: 32.0, tip: 30.0, bonus: 0, total: 62.0 },
    distance: 2.1,
    duration: 10,
    completedAt: new Date(Date.now() - 97200000).toISOString(),
    rating: 5,
  },
  {
    id: "del_193",
    orderId: "ORD-48283",
    restaurant: { name: "Barcelos Fourways", address: "Fourways Mall" },
    customer: { area: "Lonehill" },
    earnings: { deliveryFee: 38.0, tip: 12.0, bonus: 5.0, total: 55.0 },
    distance: 4.0,
    duration: 15,
    completedAt: new Date(Date.now() - 172800000).toISOString(),
    rating: 4,
  },
  {
    id: "del_192",
    orderId: "ORD-48282",
    restaurant: { name: "Vida e Caffè Braamfontein", address: "Braamfontein" },
    customer: { area: "Auckland Park" },
    earnings: { deliveryFee: 30.0, tip: 8.0, bonus: 0, total: 38.0 },
    distance: 2.8,
    duration: 11,
    completedAt: new Date(Date.now() - 176400000).toISOString(),
  },
  {
    id: "del_191",
    orderId: "ORD-48281",
    restaurant: { name: "Panarottis Benmore", address: "Benmore Gardens" },
    customer: { area: "Morningside" },
    earnings: { deliveryFee: 44.0, tip: 18.0, bonus: 10.0, total: 72.0 },
    distance: 5.5,
    duration: 19,
    completedAt: new Date(Date.now() - 180000000).toISOString(),
    rating: 5,
  },
  {
    id: "del_190",
    orderId: "ORD-48280",
    restaurant: { name: "Wimpy Norwood", address: "Norwood Mall" },
    customer: { area: "Houghton" },
    earnings: { deliveryFee: 36.0, tip: 5.0, bonus: 0, total: 41.0 },
    distance: 3.9,
    duration: 14,
    completedAt: new Date(Date.now() - 259200000).toISOString(),
    rating: 4,
  },
  {
    id: "del_189",
    orderId: "ORD-48279",
    restaurant: { name: "Fishaways Eastgate", address: "Eastgate Mall" },
    customer: { area: "Bedfordview" },
    earnings: { deliveryFee: 48.0, tip: 20.0, bonus: 15.0, total: 83.0 },
    distance: 6.8,
    duration: 23,
    completedAt: new Date(Date.now() - 262800000).toISOString(),
    rating: 5,
  },
];

export const mockEarnings: Record<string, EarningsData> = {
  today: {
    period: "today",
    deliveryFees: 125.0,
    tips: 30.0,
    incentives: 5.0,
    total: 160.0,
    deliveryCount: 3,
    hoursOnline: 2.5,
    earningsPerHour: 64.0,
  },
  week: {
    period: "week",
    deliveryFees: 1845.0,
    tips: 423.0,
    incentives: 120.0,
    total: 2388.0,
    deliveryCount: 42,
    hoursOnline: 32.5,
    earningsPerHour: 73.48,
  },
  month: {
    period: "month",
    deliveryFees: 7280.0,
    tips: 1650.0,
    incentives: 480.0,
    total: 9410.0,
    deliveryCount: 168,
    hoursOnline: 128.0,
    earningsPerHour: 73.52,
  },
};

export const mockPayouts: Payout[] = [
  {
    id: "pay_010",
    amount: 2150.0,
    date: "2026-03-04",
    status: "completed",
    method: "FNB Cheque Account",
  },
  {
    id: "pay_009",
    amount: 2340.0,
    date: "2026-02-25",
    status: "completed",
    method: "FNB Cheque Account",
  },
  {
    id: "pay_008",
    amount: 1980.0,
    date: "2026-02-18",
    status: "completed",
    method: "FNB Cheque Account",
  },
  {
    id: "pay_007",
    amount: 2510.0,
    date: "2026-02-11",
    status: "completed",
    method: "FNB Cheque Account",
  },
  {
    id: "pay_006",
    amount: 2050.0,
    date: "2026-02-04",
    status: "completed",
    method: "FNB Cheque Account",
  },
];
